Repository zurichat/zc_plugin_company_holiday_calendar, pull requests merged in 2021-09, with the labels that each got.

#193 styled and positioned arrow buttons
  calendar_frontend/src/css/react-big-calendar.css
Labels: Accepted

#194 Event Form radio button groups
  calendar_frontend/.gitignore
  calendar_frontend/package-lock.json
  calendar_frontend/src/App.js
  calendar_frontend/src/conponents/Event.js
  calendar_frontend/src/conponents/showMe/ShowMe.css
  calendar_frontend/src/conponents/showMe/ShowMe.js
  calendar_frontend/yarn.lock
Labels: Approved

#199 modified event.css
  calendar_frontend/src/conponents/event.css
  calendar_frontend/src/index.css
Labels: Approved

#363 datastore for data persistency to zc core
  calendar_backend/Core/__init__.py
  calendar_backend/Core/tests.py
  calendar_backend/Core/utils.py
  calendar_backend/calendar_backend/settings.py
  calendar_backend/calendar_backend/urls.py
  calendar_backend/calendarapp/datastore.py
  calendar_backend/requirements.txt
Labels: Accepted, Backend, Approved
